'use client'

import { useState, useEffect } from 'react'
import { Pencil, Trash2, ChevronLeft, ChevronRight } from 'lucide-react'
import { toast } from 'sonner'
import { createClient } from '@/lib/supabase/client'
import { formatCurrency, formatDate } from '@/lib/utils'
import { IncomeModal } from './income-modal'
import { MultiSelect } from '@/components/ui/multi-select'
import type { BudgetPeriod, Category, CategorySummaryItem, Income, PaymentMode, Subcategory } from '@/lib/types'
import { cn } from '@/lib/utils'
import { CategorySpendCards } from '@/components/category-spend-cards'

const PAGE_SIZE = 50

interface IncomeListClientProps {
  incomes: Income[]
  totalCount: number
  paymentModes: PaymentMode[]
  budgetPeriods: BudgetPeriod[]
  categories: Category[]
  categorySummary: CategorySummaryItem[]
  subcategories: Subcategory[]
  enableSubcategories: boolean
  currency: string
  page: number
  filters: {
    search: string
    paymentIds: string[]
    categoryIds: string[]
    types: string[]
    subcategoryIds: string[]
    sort: string
    dateFrom: string
    dateTo: string
  }
  onFilterChange: (key: string, value: string | string[]) => void
  onPageChange: (page: number) => void
  onRefresh: () => void
}

export function IncomeListClient({
  incomes,
  totalCount,
  paymentModes,
  budgetPeriods,
  categories,
  categorySummary,
  subcategories,
  enableSubcategories,
  currency,
  page,
  filters,
  onFilterChange,
  onPageChange,
  onRefresh,
}: IncomeListClientProps) {
  const [editTarget, setEditTarget] = useState<Income | null>(null)
  const [modalOpen, setModalOpen] = useState(false)
  const supabase = createClient()

  const [localIncomes, setLocalIncomes] = useState<Income[]>(incomes)
  const [localCount, setLocalCount] = useState(totalCount)
  useEffect(() => { setLocalIncomes(incomes) }, [incomes])
  useEffect(() => { setLocalCount(totalCount) }, [totalCount])

  const totalPages = Math.ceil(localCount / PAGE_SIZE)

  const handleEdit = (income: Income) => {
    setEditTarget(income)
    setModalOpen(true)
  }

  const handleDelete = async (id: string, autoGenerated: boolean) => {
    const msg = autoGenerated ? 'Delete this auto-generated income entry?' : 'Delete this income entry?'
    if (!confirm(msg)) return
    setLocalIncomes(prev => prev.filter(i => i.id !== id))
    setLocalCount(prev => Math.max(0, prev - 1))
    const { error } = await supabase.from('incomes').delete().eq('id', id)
    if (error) { toast.error(error.message); onRefresh(); return }
    toast.success('Income deleted')
    onRefresh()
  }

  const handleIncomeSuccess = (income: Income, isEdit: boolean) => {
    if (isEdit) {
      setLocalIncomes(prev => prev.map(i => i.id === income.id ? income : i))
    } else {
      setLocalIncomes(prev => [income, ...prev])
      setLocalCount(prev => prev + 1)
    }
    onRefresh()
  }

  const selectCls = cn(
    'px-3 py-1.5 text-xs bg-[var(--elevated)] border border-[var(--border)] rounded-[var(--radius-sm)]',
    'text-[var(--ink)] focus:outline-none focus:ring-2 focus:ring-[var(--c-save)]',
  )

  const desktopHeaders = enableSubcategories
    ? ['Date', 'Description', 'Category', 'Subcategory', 'Account', 'Amount']
    : ['Date', 'Description', 'Category', 'Account', 'Amount']

  return (
    <>
      {/* Category spend cards */}
      {categorySummary.some((i) => i.show_in_cards) && (
        <div className="mb-4">
          <CategorySpendCards items={categorySummary} currency={currency} accentColor="var(--c-save)" />
        </div>
      )}

      {/* Filters row */}
      <div className="flex flex-wrap gap-2 items-center mb-4">
        <input
          type="search"
          placeholder="Search description, notes..."
          value={filters.search}
          onChange={(e) => onFilterChange('search', e.target.value)}
          className="px-3 py-1.5 text-xs bg-[var(--elevated)] border border-[var(--border)] rounded-[var(--radius-sm)]
            text-[var(--ink)] placeholder:text-[var(--ink-subtle)]
            focus:outline-none focus:ring-2 focus:ring-[var(--c-save)] flex-1 min-w-40"
        />

        <MultiSelect
          options={categories.map(c => ({ value: c.id, label: c.name, color: c.color }))}
          value={filters.categoryIds}
          onChange={(v) => onFilterChange('categoryIds', v)}
          placeholder="All categories"
          accentColor="var(--c-save)"
        />

        {enableSubcategories && (
          <MultiSelect
            options={subcategories.map(s => ({ value: s.id, label: s.name, color: s.color }))}
            value={filters.subcategoryIds}
            onChange={(v) => onFilterChange('subcategoryIds', v)}
            placeholder="All subcategories"
            accentColor="var(--c-save)"
          />
        )}

        <MultiSelect
          options={[
            { value: 'Need', label: 'Need' },
            { value: 'Want', label: 'Want' },
            { value: 'Saving', label: 'Saving' },
          ]}
          value={filters.types}
          onChange={(v) => onFilterChange('types', v)}
          placeholder="All types"
          accentColor="var(--c-save)"
        />

        <MultiSelect
          options={paymentModes.map(pm => ({ value: pm.id, label: pm.name }))}
          value={filters.paymentIds}
          onChange={(v) => onFilterChange('paymentIds', v)}
          placeholder="All accounts"
          accentColor="var(--c-save)"
        />

        <select value={filters.sort} onChange={(e) => onFilterChange('sort', e.target.value)} className={selectCls}>
          <option value="date_desc">Newest first</option>
          <option value="date_asc">Oldest first</option>
          <option value="amount_desc">Largest first</option>
          <option value="amount_asc">Smallest first</option>
        </select>
      </div>

      {/* Summary line */}
      <p className="text-xs text-[var(--ink-muted)] mb-3 tabular-nums">
        {localCount} {localCount === 1 ? 'entry' : 'entries'}
        {localCount > 0 && (
          <> · Total: <strong className="text-[var(--ink)]">
            {formatCurrency(localIncomes.reduce((s, i) => s + Number(i.amount), 0), currency)}
          </strong> (this page)</>
        )}
      </p>

      {localIncomes.length === 0 ? (
        <div className="py-16 text-center text-sm text-[var(--ink-muted)]">
          No income found
        </div>
      ) : (
        <>
          {/* Desktop table */}
          <div className="hidden sm:block border border-[var(--border)] rounded-[var(--radius-sm)] overflow-hidden">
            <table className="w-full">
              <thead>
                <tr className="bg-[var(--surface)] border-b border-[var(--border)]">
                  {desktopHeaders.map((h) => (
                    <th key={h} className="px-4 py-2.5 text-left text-xs font-semibold
                      text-[var(--ink-muted)] uppercase tracking-wide whitespace-nowrap">
                      {h}
                    </th>
                  ))}
                  <th className="px-4 py-2.5 w-16" />
                </tr>
              </thead>
              <tbody className="divide-y divide-[var(--border)]">
                {localIncomes.map((income) => (
                  <tr
                    key={income.id}
                    className="group bg-[var(--elevated)] hover:bg-[var(--surface)] cursor-pointer transition-colors"
                    onClick={() => handleEdit(income)}
                  >
                    <td className="px-4 py-3 text-xs tabular-nums text-[var(--ink-muted)] whitespace-nowrap">
                      {formatDate(income.date, 'dd MMM yyyy')}
                    </td>
                    <td className="px-4 py-3 text-sm max-w-[220px]">
                      <div className="flex items-center gap-2">
                        <span className="w-2 h-2 rounded-full shrink-0"
                          style={{ backgroundColor: income.auto_generated ? 'var(--c-primary)' : 'var(--c-save)' }} />
                        <span className="truncate text-[var(--ink-muted)] text-xs">
                          {income.description || <em className="not-italic text-[var(--ink-subtle)]">No description</em>}
                        </span>
                        {income.auto_generated && (
                          <span className="text-[10px] font-medium px-1.5 py-0.5 rounded-[var(--radius-xs)]
                            bg-[var(--surface-2)] text-[var(--ink-muted)] shrink-0">
                            auto
                          </span>
                        )}
                      </div>
                      {income.notes && (
                        <div className="text-xs text-[var(--ink-subtle)] truncate mt-0.5 pl-4">{income.notes}</div>
                      )}
                    </td>
                    <td className="px-4 py-3 text-xs text-[var(--ink-muted)] whitespace-nowrap">
                      {income.category ? (
                        <div className="flex items-center gap-1.5">
                          <span className="w-2 h-2 rounded-full shrink-0"
                            style={{ backgroundColor: income.category.color }} />
                          <span className="truncate max-w-[100px]">{income.category.name}</span>
                        </div>
                      ) : (
                        <span className="text-[var(--ink-subtle)]">—</span>
                      )}
                    </td>
                    {enableSubcategories && (
                      <td className="px-4 py-3 text-xs text-[var(--ink-muted)] whitespace-nowrap">
                        {income.subcategory ? (
                          <div className="flex items-center gap-1.5">
                            <span className="w-2 h-2 rounded-full shrink-0"
                              style={{ backgroundColor: income.subcategory.color }} />
                            <span className="truncate max-w-[100px]">{income.subcategory.name}</span>
                          </div>
                        ) : (
                          <span className="text-[var(--ink-subtle)]">—</span>
                        )}
                      </td>
                    )}
                    <td className="px-4 py-3 text-xs text-[var(--ink-muted)] whitespace-nowrap">
                      {income.payment_mode?.name}
                    </td>
                    <td className="px-4 py-3 text-sm font-semibold tabular-nums whitespace-nowrap"
                      style={{ color: 'var(--c-save)' }}>
                      +{formatCurrency(Number(income.amount), currency)}
                    </td>
                    <td className="px-4 py-3 whitespace-nowrap">
                      <div className="flex items-center gap-1 flex">
                        <button
                          onClick={(e) => { e.stopPropagation(); handleEdit(income) }}
                          className="p-1.5 rounded-[var(--radius-sm)] text-[var(--ink-subtle)] hover:text-[var(--c-primary)]
                            hover:bg-[var(--elevated)] transition-colors"
                          title="Edit"
                        >
                          <Pencil size={12} />
                        </button>
                        <button
                          onClick={(e) => { e.stopPropagation(); handleDelete(income.id, income.auto_generated) }}
                          className="p-1.5 rounded-[var(--radius-sm)] text-[var(--ink-subtle)] hover:text-[var(--c-want)]
                            hover:bg-[var(--tint-want)] transition-colors"
                          title="Delete"
                        >
                          <Trash2 size={12} />
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* Mobile card list */}
          <div className="sm:hidden divide-y divide-[var(--border)]">
            {localIncomes.map((income) => (
              <div
                key={income.id}
                className="group flex items-center gap-3 py-3 cursor-pointer"
                onClick={() => handleEdit(income)}
              >
                <span
                  className="w-2 h-2 rounded-full shrink-0 mt-0.5"
                  style={{
                    backgroundColor: income.category?.color
                      ?? (income.auto_generated ? 'var(--c-primary)' : 'var(--c-save)'),
                  }}
                />
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-1.5">
                    <span className="text-sm font-medium text-[var(--ink)] truncate">
                      {income.description || income.payment_mode?.name || 'Income'}
                    </span>
                    {income.auto_generated && (
                      <span className="text-[10px] px-1 py-0.5 rounded bg-[var(--surface-2)] text-[var(--ink-muted)] shrink-0">
                        auto
                      </span>
                    )}
                  </div>
                  <div className="flex items-center gap-1.5 mt-0.5 flex-wrap">
                    {income.category && (
                      <>
                        <span className="text-xs text-[var(--ink-muted)]">{income.category.name}</span>
                        <span className="text-xs text-[var(--ink-subtle)]">·</span>
                      </>
                    )}
                    {enableSubcategories && income.subcategory && (
                      <>
                        <span className="text-xs text-[var(--ink-muted)]">{income.subcategory.name}</span>
                        <span className="text-xs text-[var(--ink-subtle)]">·</span>
                      </>
                    )}
                    <span className="text-xs text-[var(--ink-muted)]">{income.payment_mode?.name}</span>
                    <span className="text-xs text-[var(--ink-subtle)]">·</span>
                    <span className="text-xs text-[var(--ink-subtle)] tabular-nums">
                      {formatDate(income.date, 'dd MMM')}
                    </span>
                  </div>
                </div>
                <div className="flex items-center gap-2 shrink-0">
                  <span className="text-sm font-semibold tabular-nums" style={{ color: 'var(--c-save)' }}>
                    +{formatCurrency(Number(income.amount), currency)}
                  </span>
                  <div className="flex items-center gap-0.5 flex">
                    <button
                      onClick={(e) => { e.stopPropagation(); handleEdit(income) }}
                      className="p-1.5 rounded text-[var(--ink-subtle)] hover:text-[var(--c-primary)] transition-colors"
                      title="Edit"
                    >
                      <Pencil size={12} />
                    </button>
                    <button
                      onClick={(e) => { e.stopPropagation(); handleDelete(income.id, income.auto_generated) }}
                      className="p-1.5 rounded text-[var(--ink-subtle)] hover:text-[var(--c-want)] transition-colors"
                      title="Delete"
                    >
                      <Trash2 size={12} />
                    </button>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </>
      )}

      {/* Pagination */}
      {totalPages > 1 && (
        <div className="flex items-center justify-between mt-4">
          <span className="text-xs text-[var(--ink-muted)] tabular-nums">
            Page {page} of {totalPages}
          </span>
          <div className="flex gap-1">
            <button
              onClick={() => onPageChange(page - 1)}
              disabled={page <= 1}
              className="p-1.5 rounded-[var(--radius-sm)] border border-[var(--border)] text-[var(--ink-muted)]
                hover:text-[var(--ink)] disabled:opacity-40 disabled:cursor-not-allowed transition-colors"
            >
              <ChevronLeft size={14} />
            </button>
            <button
              onClick={() => onPageChange(page + 1)}
              disabled={page >= totalPages}
              className="p-1.5 rounded-[var(--radius-sm)] border border-[var(--border)] text-[var(--ink-muted)]
                hover:text-[var(--ink)] disabled:opacity-40 disabled:cursor-not-allowed transition-colors"
            >
              <ChevronRight size={14} />
            </button>
          </div>
        </div>
      )}

      <IncomeModal
        open={modalOpen}
        onOpenChange={(open) => {
          setModalOpen(open)
          if (!open) setEditTarget(null)
        }}
        income={editTarget}
        paymentModes={paymentModes}
        budgetPeriods={budgetPeriods}
        categories={categories}
        subcategories={subcategories}
        enableSubcategories={enableSubcategories}
        onSuccess={handleIncomeSuccess}
        currency={currency}
      />
    </>
  )
}
