'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { Plus, Pencil, Trash2, TrendingUp, TrendingDown, Wallet } from 'lucide-react'
import { toast } from 'sonner'
import { createClient } from '@/lib/supabase/client'
import { formatCurrency, formatDate } from '@/lib/utils'
import { IncomeModal } from './income-modal'
import type { BudgetPeriod, Income, PaymentMode, PaymentModeBalance } from '@/lib/types'

interface IncomePageClientProps {
  incomes: Income[]
  balances: PaymentModeBalance[]
  paymentModes: PaymentMode[]
  budgetPeriods: BudgetPeriod[]
  currency: string
}

export function IncomePageClient({
  incomes,
  balances,
  paymentModes,
  budgetPeriods,
  currency,
}: IncomePageClientProps) {
  const router = useRouter()
  const supabase = createClient()
  const [modalOpen, setModalOpen] = useState(false)
  const [editTarget, setEditTarget] = useState<Income | null>(null)

  const handleEdit = (income: Income) => {
    setEditTarget(income)
    setModalOpen(true)
  }

  const handleAdd = () => {
    setEditTarget(null)
    setModalOpen(true)
  }

  const handleDelete = async (id: string, autoGenerated: boolean) => {
    const msg = autoGenerated
      ? 'Delete this auto-generated income entry? It was created from a budget period income schedule.'
      : 'Delete this income entry?'
    if (!confirm(msg)) return
    const { error } = await supabase.from('incomes').delete().eq('id', id)
    if (error) { toast.error(error.message); return }
    toast.success('Income deleted')
    router.refresh()
  }

  const totalIncome = incomes.reduce((s, i) => s + Number(i.amount), 0)

  return (
    <>
      <div className="page-enter flex flex-col gap-6 p-6 max-w-6xl mx-auto w-full">
        {/* Header */}
        <div className="flex items-start justify-between gap-4">
          <div>
            <div className="inline-flex items-center px-2 py-0.5 mb-2 rounded-full text-[10px] font-bold
              uppercase tracking-widest text-white"
              style={{ backgroundColor: 'var(--c-save)' }}>
              Income
            </div>
            <h1 className="font-display text-3xl font-medium tracking-tight text-[var(--ink)]">
              Income & Balance
            </h1>
          </div>
          <button
            onClick={handleAdd}
            className="btn-primary shrink-0"
            style={{ backgroundColor: 'var(--c-save)' }}
          >
            <Plus size={14} /> Add income
          </button>
        </div>

        {/* Balance cards per payment mode */}
        {balances.length > 0 && (
          <section>
            <div className="flex items-center gap-2 mb-3">
              <span className="section-bar" style={{ backgroundColor: 'var(--c-save)' }} />
              <h2 className="font-display text-lg font-medium text-[var(--ink)]">Account balances</h2>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
              {balances.map((b) => (
                <div key={b.id} className="apple-card overflow-hidden">
                  <div className="h-1" style={{
                    backgroundColor: b.balance >= 0 ? 'var(--c-save)' : 'var(--c-want)'
                  }} />
                  <div className="p-4">
                    <div className="flex items-center gap-2 mb-3">
                      <Wallet size={14} className="text-[var(--ink-muted)]" />
                      <p className="text-xs font-semibold text-[var(--ink-muted)] uppercase tracking-wide">
                        {b.name}
                      </p>
                    </div>
                    <p className="font-display text-2xl font-medium tabular-nums"
                      style={{ color: b.balance >= 0 ? 'var(--c-save)' : 'var(--c-want)' }}>
                      {b.balance < 0 ? '-' : ''}{formatCurrency(Math.abs(b.balance), currency)}
                    </p>
                    <div className="flex items-center gap-3 mt-2">
                      <span className="flex items-center gap-1 text-xs text-[var(--c-save)] tabular-nums">
                        <TrendingUp size={10} />
                        {formatCurrency(b.income_total, currency)}
                      </span>
                      <span className="text-[var(--ink-subtle)] text-xs">·</span>
                      <span className="flex items-center gap-1 text-xs text-[var(--c-want)] tabular-nums">
                        <TrendingDown size={10} />
                        {formatCurrency(b.expense_total, currency)}
                      </span>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </section>
        )}

        {/* Income list */}
        <section className="apple-card p-5">
          <div className="flex items-center gap-2 mb-4">
            <span className="section-bar" style={{ backgroundColor: 'var(--c-save)' }} />
            <h2 className="font-display text-base font-medium text-[var(--ink)]">All income</h2>
            {totalIncome > 0 && (
              <span className="ml-auto text-sm font-medium tabular-nums text-[var(--c-save)]">
                Total: {formatCurrency(totalIncome, currency)}
              </span>
            )}
          </div>

          {incomes.length === 0 ? (
            <div className="py-12 text-center">
              <p className="text-sm text-[var(--ink-muted)]">No income recorded yet.</p>
              <p className="text-xs text-[var(--ink-subtle)] mt-1">
                Add income manually or enable income tracking in a budget period.
              </p>
            </div>
          ) : (
            <div className="divide-y divide-[var(--border)]">
              {incomes.map((income) => (
                <div
                  key={income.id}
                  className="group flex items-center gap-3 py-3 px-2 hover:bg-[var(--surface-2)]
                    rounded-[var(--radius-md)] transition-colors cursor-pointer"
                  onClick={() => handleEdit(income)}
                >
                  {/* Green dot indicator */}
                  <div className="w-2 h-2 rounded-full shrink-0" style={{
                    backgroundColor: income.auto_generated ? 'var(--c-primary)' : 'var(--c-save)'
                  }} />

                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 flex-wrap">
                      <span className="text-sm font-medium text-[var(--ink)] truncate">
                        {income.description}
                      </span>
                      {income.auto_generated && (
                        <span className="text-[10px] font-medium px-1.5 py-0.5 rounded-[var(--radius-xs)]
                          bg-[var(--surface-2)] text-[var(--ink-muted)]">
                          auto
                        </span>
                      )}
                    </div>
                    <div className="flex items-center gap-2 mt-0.5">
                      <span className="text-xs text-[var(--ink-muted)]">
                        {income.payment_mode?.name}
                      </span>
                      <span className="text-xs text-[var(--ink-subtle)]">·</span>
                      <span className="text-xs text-[var(--ink-muted)] tabular-nums">
                        {formatDate(income.date, 'dd MMM yyyy')}
                      </span>
                    </div>
                  </div>

                  <span className="tabular-nums text-sm font-semibold shrink-0"
                    style={{ color: 'var(--c-save)' }}>
                    +{formatCurrency(Number(income.amount), currency)}
                  </span>

                  <div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity shrink-0">
                    <button
                      onClick={(e) => { e.stopPropagation(); handleEdit(income) }}
                      className="p-1.5 rounded-[var(--radius-md)] text-[var(--ink-subtle)]
                        hover:text-[var(--c-primary)] hover:bg-[var(--elevated)] transition-colors"
                      title="Edit"
                    >
                      <Pencil size={12} />
                    </button>
                    <button
                      onClick={(e) => { e.stopPropagation(); handleDelete(income.id, income.auto_generated) }}
                      className="p-1.5 rounded-[var(--radius-md)] text-[var(--ink-subtle)]
                        hover:text-[var(--c-want)] hover:bg-[var(--tint-want)] transition-colors"
                      title="Delete"
                    >
                      <Trash2 size={12} />
                    </button>
                  </div>
                </div>
              ))}
            </div>
          )}
        </section>
      </div>

      {/* FAB on mobile */}
      <button
        onClick={handleAdd}
        className="md:hidden fixed bottom-20 right-4 z-30 w-14 h-14 rounded-full
          flex items-center justify-center transition-transform hover:scale-105 active:scale-95"
        style={{ backgroundColor: 'var(--c-save)', color: '#fff', boxShadow: 'var(--shadow-lg)' }}
        aria-label="Add income"
      >
        <Plus size={22} />
      </button>

      <IncomeModal
        open={modalOpen}
        onOpenChange={setModalOpen}
        income={editTarget}
        paymentModes={paymentModes}
        budgetPeriods={budgetPeriods}
        onSuccess={() => router.refresh()}
        currency={currency}
      />
    </>
  )
}
